.launched,.loading,.removing,.unconfirmedNames,.unconfirmedLinks,.unconfirmedAscii,.appPath,.dappsPath,.sandboxes,.dappready,.routes,.unconfirmedOutTansfers,.attachApi,.get,.getByIds,.list,.createBasePathes,.installDependencies,.getInstalledIds,.removeDApp,.downloadDApp,.symlink,.apiHandler,.getFile,.getIcon,.dappRoutes,.launch,.downloadSiaFile,.launchApp,.stop,.addTransactions