@startuml ../../../styles/images/modules/blocks/blocks-activity.png
skinparam BorderColor #blue\9932CC
skinparam backgroundcolor AntiqueWhite/white

title
区款链同步与创建流程图

end title

footer copyright (c) imfly 2016.07.23 http://bitcoin-on-nodejs.ebookchain.org
header 《Nodejs开发加密货币》分析用图：《区块链》

(*) --> 启动应用

partition "写入创世区块" {
  --> app.js: new Blocks()
  --> blocks.js: saveGenesisBlock()
  --> blocks.js: saveBlock()
  --> logic/block.js: dbSave()
}

--> [节点准备完毕] library.bus.message('peerReady')
note right: 触发事件

--> (*)
@enduml
