@startuml ../../../styles/images/modules/transactions/signTransaction-activity.png
skinparam BorderColor #blue\9932CC
skinparam backgroundcolor AntiqueWhite/white

title
交易签名流程图

end title

footer copyright (c) imfly 2016.07.05 http://ebookchain.org
header 《Nodejs开发加密货币》分析用图：《交易》

' shared.addTransactions()代码逻辑

(*)--> [新建交易] "put /api/transactions/" as inputForm
note left: 代码在shared.addTransactions()方法里

--> "请看上一步：1.整理交易数据"

' logic.transaction.create()处理逻辑
partition "2.给合法交易签名" {
  --> "将交易信息交给logic.transaction.create()进一步处理"
  note left: 代码在logic.transaction.create()方法里

  --> "添加时间戳: timestamp: slots.getTime()"
  note left
  "这里的时间戳不是直接使用Date.now()获得，而是
  亿书系统统一处理的。请看书中有关时间戳的论述"
  end note

  --> "甲方签名: trs.signature = this.sign(data.keypair, trs)"
  --> "如果有支付密码，甲方进行二次签名: trs.signSignature = this.sign(data.secondKeypairtrs);"
  --> "计算交易ID（getId())"
  note left
  "交易ID不是一个简单的随机数，
  而是与交易类型、时间戳、甲乙方密钥、
  地址、交易数额等直接相关的Hash值"
  end note
  --> "计算交易费用（fee）"
}

--> "请看下一步： 3.验证交易合法性"

--> (*)
@enduml
