@startuml ../../../styles/images/modules/peer/class.png
skinparam BorderColor #blue\9932CC
skinparam backgroundcolor AntiqueWhite/white

title
Peer类图及其关联关系

end title
footer copyright (c) imfly 2016.03.01 http://bitcoin-on-nodejs.ebookchain.org
header 《Nodejs开发加密货币》第八篇分析用图

' modules/Peer.js
Class Peer {
  - modules: array
  - library: array
  - privated： hash
  - shared: hash
  ====
  .. private methods ..
  -attachApi(): void
  -updatePeerList(cb): void
  -count(cb): void
  -banManager(cb): void
  -getByFilter(cb): void

  .. public methods ..
  +list(options, cb): rows
  +state(pip, port, state, timeoutSeconds, cb): rows
  +remove(pip, port, cb): void
  +addDapp(config, cb): void
  +update(peer, cb): void
  +sandboxApi(call, args, cb): void

  .. events ..
  +onBind(scope): void
  +onBlockchainReady(scope)
  +onPeerReady(): void

  .. shared methods..
  -getPeers(req, cb): void
  -getPeer(req, cb): void
  -version(req, cb): void
}

' helper/router.js
Class Router {
  +map(root, config): *
}

' relationship
Bus <- Peer: library.bus.message('bind')
note top on link
触发事件
--
自己实现的事件处理方法，简单实用
end note

Peer -> Transport: modules.transport.getFromRandomPeer()
Peer <- Transport: modules.peer.list()
Peer -up-> Router: router.map(shared, {})
note right
  一个简单的辅助类
  ====
  * 其他实例通过请求 ""map()"" 方法映射路由
end note
Peer -down-> dbLite: library.dbLite.query()
@enduml
