@startuml ../../../styles/images/modules/crypto/activity.png
  skinparam BorderColor #blue\9932CC
  skinparam backgroundcolor AntiqueWhite/white

  title
  Accounts中生成用户ID流程图

  end title

  footer copyright (c) imfly 2016.03.10 http://book.btcnodejs.com
  header 《Nodejs开发加密货币》第九篇分析用图

  (*) --> [从接口方法开始] "post `/api/accounts/generatePublicKey`"
  --> shared.generatePublickey()
  --> private.openAccount(secret, cb)
  --> hash = crypto.createHash('sha256').update(secret, 'utf8').digest();
  --> ed.MakeKeypair(hash);
  --> setAccountAndGet(data, cb);
  --> self.generateAddressByPublicKey(data.publicKey)
  --> (*)
@enduml
