@startuml ../../../styles/images/helpers/milestones/activity.png
skinparam BorderColor #blue\9932CC
skinparam backgroundcolor AntiqueWhite/white

title
helpers/milestones类主要函数调用流程图

end title

footer copyright (c) imfly 2016.03.09 http://bitcoin-on-nodejs.ebookchain.org
header 《Nodejs开发加密货币》第x篇分析用图

(*) -right-> [给定某个块高度height] "计算相对高度值parseHeight(height)"

note right
这里预先设定了转折点的间隔量distance = 3000000
以及每个间隔的起点rewardOffset = 60480，这样，
我们就能够简单的确认该高度处在哪个间隔期内，
即：location = (height-rewardOffset)/distance
end note

if location > 最大里程碑(4) then
--> [yes] "最大里程碑(4)"
--> "获得当前所处转折点" as milestone
else
--> [no] location
--> milestone
endif

--> 计算当前应该获得的奖励

note right
其实，这里有个简单的逻辑，当未达到奖励起点位置时，
奖励为0，大于设定最大里程碑位置时，奖励都按最大
里程碑的奖励额度计算
end note

--> (*)
@enduml
